[package]
name = "arb-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"]}
serde_json = "*"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
serde = { version = "1.0.197", features = ["derive"] }
csv = "1.3.0"


# For fastwebsockets
# tokio-rustls = "0.24.0"
# hyper-util = { version = "0.1.0", features = ["tokio"] }
# rustls-pemfile = "1.0"
# http-body-util = { version = "0.1.0" }
# hyper = { version = "1", features = ["http1", "server", "client"] }
# assert2 = "0.3.4"
# trybuild = "1.0.80"
# criterion = "0.4.0"
# anyhow = "1.0.71"
# webpki-roots = "0.23.0"
# bytes = "1.4.0"
# axum = "0.7.4"
# fastwebsockets = {version = "*", features = ["upgrade"]}
