[package]
name = "arb-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"]}
serde_json = "*"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
serde = { version = "1.0.197", features = ["derive"] }
csv = "1.3.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
futures = "0.3.3"
thiserror = "*"
chrono = "0.4.38"
reqwest = {version="0.12.4", features = ["json"]}
tokio-stream = { version = "0.1.9", features = ["sync"] }
pin-project = "1.1.5"
async-trait = "0.1.57"